#!/bin/bash

function apt_base_packages {
	echo "Installing base packages."
	apt-get install -y zsh tmux htop vim curl gpg zip jq peco
}

function brew_base_packages {
	echo "Installing base packages."
	brew install tmux htop curl gpg reattach-to-user-namespace peco
}

system_type=$(uname -s)

cd "$HOME"

echo "Init submodules"
#yadm submodule update --recursive --init

if [ "$system_type" = "Darwin" ]; then
	echo "I'm a MacOS system."
	if [ ! command -v brew >/dev/null 2>&1 ]; then
		echo "Installing homebrew"
		/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	fi
	brew_base_packages
fi

if [ "$system_type" = "Linux" ]; then
	echo "I'm a Linux system."
	if [ "$(lsb_release -is)" = "Ubuntu" ] || [ "$(lsb_release -is)" = "Ubuntu" ] ; then
		echo "I'm an apt-based system."
		apt_base_packages
	fi
fi

if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

ZPLUG_HOME = $HOME/.zplug

if [ ! -d "$ZPLUG_HOME" ]; then
	echo "Installing zplug"
	curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
	zsh -c 'source .zshrc && zplug install'
fi
if [ ! -d ".powerline_fonts" ]; then
	git clone https://github.com/powerline/fonts.git --depth=1 .powerline_fonts
	cd .powerline_fonts && bash install.sh
fi
