#!/bin/bash

function apt_base_packages {
	echo "Installing base packages."
	apt-get install -y zsh tmux htop vim curl gpg zip jq 
}

function brew_base_packages {
	echo "Installing base packages."
	brew install tmux htop curl gpg reattach-to-user-namespace
}

system_type=$(uname -s)

cd "$HOME"

echo "Init submodules"
#yadm submodule update --recursive --init

if [ "$system_type" = "Darwin" ]; then
	echo "I'm a MacOS system."
	if [ ! command -v brew >/dev/null 2>&1 ]; then
		echo "Installing homebrew"
		/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	fi
	brew_base_packages
fi

if [ "$system_type" = "Linux" ]; then
	echo "I'm a Linux system."
	if [ "$(lsb_release -is)" = "Ubuntu" ] || [ "$(lsb_release -is)" = "Ubuntu" ] ; then
		echo "I'm an apt-based system."
		apt_base_packages
	fi
fi

if command -v vim >/dev/null 2>&1; then
	echo "Bootstraping Vim"
	su $SUDO_USER -c "vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'"
fi

ZPLUG_HOME = $HOME/.zplug

if [ ! -d "$ZPLUG_HOME" ]; then
	echo "Installing zplug"
	su $SUDO_USER -c "curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh"
	su $SUDO_USER -l -c "zsh -c 'source .zshrc && zplug install'"
fi

